import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "../components/TopBar";
import AuthProvider from "../providers/AuthProvider";
import MUIThemeProvider from "../providers/MUIThemeProvider";
import { EmotionCacheProvider } from "../providers/EmotionCacheProvider";
import { getServerSession } from "next-auth";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { authOptions } from "@/lib/auth";
import { Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: need to redirect to /login if not logged in


  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <ReactQueryProvider>
            <MUIThemeProvider>
              <EmotionCacheProvider>
                <TopBar />
                <Box maxWidth="100vw" paddingTop={"2em"}>
                  {children}
                </Box>
              </EmotionCacheProvider>
            </MUIThemeProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
