version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo
    command: ["mongod", "--quiet"]
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - expense-manager:/data/db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  expense-manager:
