version: "3.8"

services:
  mongo:
    container_name : mongodb
    image: mongo
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - expense-manager:/data/db

  backend:
    container_name : backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: bun run --hot src/server.ts
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    command: bun run dev
    depends_on:
      - backend

volumes:
  expense-manager:
